const HomeCarouselImages = {
  images: [
    {
      id: 1,
      path: require("../../../Assets/Images/Carsouel/carousel1.avif"),
      brand: "Brand",
      title: "Title",
      discountedPrice: "$100",
      price: "$200",
      discountPersent: "50%",
      alt: "image1",
    },
    {
      id: 2,
      path: require("../../../Assets/Images/Carsouel/carousel2.avif"),
      brand: "Brand",
      title: "Title",
      discountedPrice: "$100",
      price: "$200",
      discountPersent: "50%",
      alt: "image1",
    },
    {
      id: 3,
      path: require("../../../Assets/Images/Carsouel/carousel3.avif"),
      brand: "Brand",
      title: "Title",
      discountedPrice: "$100",
      price: "$200",
      discountPersent: "50%",
      alt: "image1",
    },
    {
      id: 4,
      path: require("../../../Assets/Images/Carsouel/carousel4.avif"),
      brand: "Brand",
      title: "Title",
      discountedPrice: "$100",
      price: "$200",
      discountPersent: "50%",
      alt: "image1",
    },
    {
      id: 5,
      path: require("../../../Assets/Images/Carsouel/carousel5.avif"),
      brand: "Brand",
      title: "Title",
      discountedPrice: "$100",
      price: "$200",
      discountPersent: "50%",
      alt: "image1",
    },
    {
      id: 6,
      path: require("../../../Assets/Images/Carsouel/carousel6.avif"),
      brand: "Brand",
      title: "Title",
      discountedPrice: "$100",
      price: "$200",
      discountPersent: "50%",
      alt: "image1",
    },
    {
      id: 7,
      path: require("../../../Assets/Images/Carsouel/carousel1.avif"),
      brand: "Brand",
      title: "Title",
      discountedPrice: "$100",
      price: "$200",
      discountPersent: "50%",
      alt: "image1",
    },
    {
      id: 8,
      path: require("../../../Assets/Images/Carsouel/carousel2.avif"),
      brand: "Brand",
      title: "Title",
      discountedPrice: "$100",
      price: "$200",
      discountPersent: "50%",
      alt: "image1",
    },
    {
      id: 9,
      path: require("../../../Assets/Images/Carsouel/carousel3.avif"),
      brand: "Brand",
      title: "Title",
      discountedPrice: "$100",
      price: "$200",
      discountPersent: "50%",
      alt: "image1",
    },
    {
      id: 10,
      path: require("../../../Assets/Images/Carsouel/carousel4.avif"),
      brand: "Brand",
      title: "Title",
      discountedPrice: "$100",
      price: "$200",
      discountPersent: "50%",
      alt: "image1",
    },
    {
      id: 11,
      path: require("../../../Assets/Images/Carsouel/carousel5.avif"),
      brand: "Brand",
      title: "Title",
      discountedPrice: "$100",
      price: "$200",
      discountPersent: "50%",
      alt: "image1",
    },
    {
      id: 6,
      path: require("../../../Assets/Images/Carsouel/carousel6.avif"),
      brand: "Brand",
      title: "Title",
      discountedPrice: "$100",
      price: "$200",
      discountPersent: "50%",
      alt: "image1",
    },
  ],
};

export default HomeCarouselImages;
