const HomeCarouselImages = {
  images: [
    {
      id: 7,
      path: require("../../../Assets/Images/Carsouel/carousel11.jpg"),
      brand: "Brand",
      title: "Title",
      discountedPrice: "$100",
      price: "$200",
      discountPersent: "50%",
      alt: "image1",
    },
    {
      id: 8,
      path: require("../../../Assets/Images/Carsouel/carousel12.jpg"),
      brand: "Brand",
      title: "Title",
      discountedPrice: "$100",
      price: "$200",
      discountPersent: "50%",
      alt: "image1",
    },
    {
      id: 9,
      path: require("../../../Assets/Images/Carsouel/carousel13.jpg"),
      brand: "Brand",
      title: "Title",
      discountedPrice: "$100",
      price: "$200",
      discountPersent: "50%",
      alt: "image1",
    },
    {
      id: 10,
      path: require("../../../Assets/Images/Carsouel/carousel14.jpg"),
      brand: "Brand",
      title: "Title",
      discountedPrice: "$100",
      price: "$200",
      discountPersent: "50%",
      alt: "image1",
    },
    {
      id: 11,
      path: require("../../../Assets/Images/Carsouel/carousel15.jpg"),
      brand: "Brand",
      title: "Title",
      discountedPrice: "$100",
      price: "$200",
      discountPersent: "50%",
      alt: "image1",
    },
    {
      id: 6,
      path: require("../../../Assets/Images/Carsouel/carousel16.jpg"),
      brand: "Brand",
      title: "Title",
      discountedPrice: "$100",
      price: "$200",
      discountPersent: "50%",
      alt: "image1",
    },
  ],
};

export default HomeCarouselImages;
