services:
  - name: trend-treasures-frontend
    type: web
    env: static
    staticPublishPath: frontend/build  # This should be 'frontend/build' for React apps.
    buildCommand: npm install && npm run build
    branch: main
    autoDeploy: true
