services:
  - name: trend-treasures-frontend
    type: web
    env: static
    staticPublishPath: /path/to/your/frontend/build
    buildCommand: npm install && npm run build
    branch: main
    autoDeploy: true

  - name: trend-treasures-backend
    type: web
    env: node
    buildCommand: npm install
    startCommand: npm start
    branch: main
    autoDeploy: true
    runtime: node
    envVars:
      DATABASE_URL: # Replace this with your actual database URL or configure via Render's dashboard.
      API_KEY: # Replace with your API key, if applicable.
