services:
  - name: trend-treasures-frontend
    type: web
    env: static
    staticPublishPath: /frontend/build
    buildCommand: npm install && npm run build
    branch: main
    autoDeploy: true

  - name: trend-treasures-backend
    type: web
    env: node
    buildCommand: npm install
    startCommand: npm start
    branch: main
    autoDeploy: true
    runtime: node
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Replace this with your actual database URL or configure via Render's dashboard.
      - key: API_KEY
        sync: false # Replace with your API key
